## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Salinopolis,BR,-0.6136,-47.3561,77.67,88,100,7.16,overcast clouds
1,1,Canutama,BR,-6.5339,-64.3831,72.79,99,100,2.21,overcast clouds
2,2,Keffi,NG,8.8486,7.8736,71.60,22,0,3.80,clear sky
3,3,Camana,PE,-16.6228,-72.7111,70.70,83,99,4.29,overcast clouds
4,4,Grindavik,IS,63.8424,-22.4338,32.90,100,100,55.23,heavy snow

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input(f'Enter the minimum temperature for your dream vacation(°F): '))
max_temp = float(input(f'Enter the maximum temperature for your dream vacation(°F): '))

Enter the minimum temperature for your dream vacation(°F): 68
Enter the maximum temperature for your dream vacation(°F): 86

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
new_city_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
new_city_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Salinopolis,BR,-0.6136,-47.3561,77.67,88,100,7.16,overcast clouds
1,1,Canutama,BR,-6.5339,-64.3831,72.79,99,100,2.21,overcast clouds
2,2,Keffi,NG,8.8486,7.8736,71.60,22,0,3.80,clear sky
3,3,Camana,PE,-16.6228,-72.7111,70.70,83,99,4.29,overcast clouds
6,6,Avarua,CK,-21.2078,-159.7750,80.65,78,20,9.22,few clouds
11,11,Sinnamary,GF,5.3833,-52.9500,76.87,89,100,7.92,overcast clouds
13,13,Esperance,AU,-33.8667,121.9000,76.84,49,14,26.35,few clouds
15,15,Bengkulu,ID,-3.8004,102.2655,81.64,70,99,10.80,moderate rain
16,16,Andros Town,BS,24.7000,-77.7667,71.56,67,3,12.48,clear sky
21,21,Talara,PE,-4.5772,-81.2719,71.60,83,62,11.27,broken clouds

In [9]:
# 4a. Determine if there are any empty rows.
new_city_df.count()

City_ID                239
City                   239
Country                238
Lat                    239
Lng                    239
Max Temp               239
Humidity               239
Cloudiness             239
Wind Speed             239
Current Description    239
dtype: int64

In [10]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_city_df = new_city_df.dropna()
clean_city_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Salinopolis,BR,-0.6136,-47.3561,77.67,88,100,7.16,overcast clouds
1,1,Canutama,BR,-6.5339,-64.3831,72.79,99,100,2.21,overcast clouds
2,2,Keffi,NG,8.8486,7.8736,71.60,22,0,3.80,clear sky
3,3,Camana,PE,-16.6228,-72.7111,70.70,83,99,4.29,overcast clouds
6,6,Avarua,CK,-21.2078,-159.7750,80.65,78,20,9.22,few clouds
11,11,Sinnamary,GF,5.3833,-52.9500,76.87,89,100,7.92,overcast clouds
13,13,Esperance,AU,-33.8667,121.9000,76.84,49,14,26.35,few clouds
15,15,Bengkulu,ID,-3.8004,102.2655,81.64,70,99,10.80,moderate rain
16,16,Andros Town,BS,24.7000,-77.7667,71.56,67,3,12.48,clear sky
21,21,Talara,PE,-4.5772,-81.2719,71.60,83,62,11.27,broken clouds

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_city_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Salinopolis,BR,77.67,overcast clouds,-0.6136,-47.3561,
1,Canutama,BR,72.79,overcast clouds,-6.5339,-64.3831,
2,Keffi,NG,71.60,clear sky,8.8486,7.8736,
3,Camana,PE,70.70,overcast clouds,-16.6228,-72.7111,
6,Avarua,CK,80.65,few clouds,-21.2078,-159.7750,
11,Sinnamary,GF,76.87,overcast clouds,5.3833,-52.9500,
13,Esperance,AU,76.84,few clouds,-33.8667,121.9000,
15,Bengkulu,ID,81.64,moderate rain,-3.8004,102.2655,
16,Andros Town,BS,71.56,clear sky,24.7000,-77.7667,
21,Talara,PE,71.60,broken clouds,-4.5772,-81.2719,

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
     # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
   
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Salinopolis,BR,77.67,overcast clouds,-0.6136,-47.3561,
1,Canutama,BR,72.79,overcast clouds,-6.5339,-64.3831,
2,Keffi,NG,71.60,clear sky,8.8486,7.8736,
3,Camana,PE,70.70,overcast clouds,-16.6228,-72.7111,
6,Avarua,CK,80.65,few clouds,-21.2078,-159.7750,
11,Sinnamary,GF,76.87,overcast clouds,5.3833,-52.9500,
13,Esperance,AU,76.84,few clouds,-33.8667,121.9000,
15,Bengkulu,ID,81.64,moderate rain,-3.8004,102.2655,
16,Andros Town,BS,71.56,clear sky,24.7000,-77.7667,
21,Talara,PE,71.60,broken clouds,-4.5772,-81.2719,

In [16]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Salinopolis,BR,77.67,overcast clouds,-0.6136,-47.3561,
1,Canutama,BR,72.79,overcast clouds,-6.5339,-64.3831,
2,Keffi,NG,71.60,clear sky,8.8486,7.8736,
3,Camana,PE,70.70,overcast clouds,-16.6228,-72.7111,
6,Avarua,CK,80.65,few clouds,-21.2078,-159.7750,
11,Sinnamary,GF,76.87,overcast clouds,5.3833,-52.9500,
13,Esperance,AU,76.84,few clouds,-33.8667,121.9000,
15,Bengkulu,ID,81.64,moderate rain,-3.8004,102.2655,
16,Andros Town,BS,71.56,clear sky,24.7000,-77.7667,
21,Talara,PE,71.60,broken clouds,-4.5772,-81.2719,

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [18]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [20]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Saving the map as a .html in the disk
from ipywidgets.embed import embed_minimal_html
embed_minimal_html('../Vacation_Search/WeatherPy_vacation_map.html', views=[fig])